baseURL = "/"
languageCode = "en-us"
title = "Prilk Consulting"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "We simplify, analyze and identify the gaps in the business, and bridge them with best practice solutions."
    meta_og_title = "Prilk Consulting"
    meta_og_type = "website"
    meta_og_url = "https://test.prilk.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "We simplify, analyze and identify the gaps in the business, and bridge them with best practice solutions."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "Solutions"
    url = "/solutions/"
    weight = 2




[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
